### ISSUE TITLE
加油！

### ISSUE THREAD

**Issue by oit63** [rongl/ROTools#1]
加油搞，争取搞个group生成folder的功能出来。

**Comment by rongl** [comment]
group生成folder..这个需要时间..我会努力的..先补上第二个功能..不是完美.但至少可以用...有bug.迟点再FIx

**Comment by oit63** [comment]
Nice+1 我已经用了一个月了， 生成Folder的功能不错

**Comment by oit63** [comment]
不过应该是有Bug， 我在某一个工程里用过一次用以后就不起作用了， 不知道是哪里影响到了。

**Comment by rongl** [comment]
Hi,您是指生成Folder的功能有Bug吗?可以给我一些数据吗?让我可以找到BUG存在哪里.

**Comment by oit63** [comment]
恩，我的工程现在用了不起作用了，你能告诉我你需要哪些信息吗？ 我想是不是不支持用了 CocoaPods 的 workspace 呢？

**Comment by rongl** [comment]
默认我已经过滤了CocoaPods的相关目录.也就说使用不会与CocoaPods互相影响.
可以给我项目左边的结构图吗?实质上是做了两步操作
1. 根据左右的结构图.创建或者移动文件.
2. 修改是与结构相关的配置文件.

**Comment by ForrestAlfred** [comment]
好的，我想是我的目录里使用了 \  / 这两个符号作文件夹名称

**Comment by oit63** [comment]
我发现问题了，如果在用ROTool生成一次目录以后，再在Xcode里面修改Group的名称，一定会失效
