### ISSUE TITLE
Does not show menu in Xcode 7.2 (7C68)

### ISSUE THREAD

**Issue by Tj3n** [rongl/ROTools#3]
Hi, I found your plugin very useful, but after i install it with Alcatraz, close and restart, the `Xcode found new bundle....` is not showing and under the `Edit` menu there's no `ROTool` submenu, I'm not sure what happen :) Please provide feedback, thanks a lot!

**Comment by rongl** [comment]
Hi,  I am sorry for this.. I will fix as soon as possible

**Comment by Tj3n** [comment]
Thanks! Hope u can fix it :D

**Comment by rongl** [comment]
Hi, Do you installed Alcatraz and normally open?

**Comment by rongl** [comment]
Please reinstall.

**Comment by Tj3n** [comment]
Sorry for the late reply, yes it seems to work perfectly now :D i will report if got any bugs, thanks!
