### ISSUE TITLE
推荐使用同步Group到文件夹的工具_Synx

### ISSUE THREAD

**Issue by oit63** [rongl/ROTools#6]
昨天有朋友推荐给我SYNX, 我试用了一下,很完美, 建议ROTools 可以不用自己实现这个功能,把SYNX 集成进来就好了. ROTools 的亮点还是集中在处理图片功能上.

**Comment by rongl** [comment]
多谢支持..因为现在很少机会再接触XCODE.所以更新会再迟一些...希望可以早点回归
